/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // All colors reference CSS custom properties so light/dark theme
        // is handled purely in CSS — no Tailwind dark: prefix needed.
        "background":                "var(--color-background)",
        "surface":                   "var(--color-surface)",
        "surface-dim":               "var(--color-surface-dim)",
        "surface-bright":            "var(--color-surface-bright)",
        "surface-container-lowest":  "var(--color-surface-container-lowest)",
        "surface-container-low":     "var(--color-surface-container-low)",
        "surface-container":         "var(--color-surface-container)",
        "surface-container-high":    "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface":                "var(--color-on-surface)",
        "on-surface-variant":        "var(--color-on-surface-variant)",
        "inverse-surface":           "var(--color-inverse-surface)",
        "inverse-on-surface":        "var(--color-inverse-on-surface)",
        "outline":                   "var(--color-outline)",
        "outline-variant":           "var(--color-outline-variant)",
        "surface-tint":              "var(--color-surface-tint)",
        "primary":                   "var(--color-primary)",
        "on-primary":                "var(--color-on-primary)",
        "primary-container":         "var(--color-primary-container)",
        "on-primary-container":      "var(--color-on-primary-container)",
        "inverse-primary":           "var(--color-inverse-primary)",
        "secondary":                 "var(--color-secondary)",
        "on-secondary":              "var(--color-on-secondary)",
        "secondary-container":       "var(--color-secondary-container)",
        "on-secondary-container":    "var(--color-on-secondary-container)",
        "secondary-fixed":           "var(--color-secondary-fixed)",
        "secondary-fixed-dim":       "var(--color-secondary-fixed-dim)",
        "tertiary":                  "var(--color-tertiary)",
        "on-tertiary":               "var(--color-on-tertiary)",
        "tertiary-container":        "var(--color-tertiary-container)",
        "on-tertiary-container":     "var(--color-on-tertiary-container)",
        "error":                     "var(--color-error)",
        "on-error":                  "var(--color-on-error)",
        "error-container":           "var(--color-error-container)",
        "on-error-container":        "var(--color-on-error-container)",
        "primary-fixed":             "var(--color-primary-fixed)",
        "primary-fixed-dim":         "var(--color-primary-fixed-dim)",
        "on-primary-fixed":          "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant":  "var(--color-on-primary-fixed-variant)",
        "on-secondary-fixed":        "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed":            "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim":        "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed":         "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-variant":           "var(--color-surface-variant)",
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans:  ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "page-margin": "4rem",
        "gutter": "2rem",
        "line-height-grid": "1.6rem",
        "stack-unit": "0.5rem",
      },
      boxShadow: {
        "paper": "var(--shadow-paper)",
        "paper-lift": "var(--shadow-paper-lift)",
        "stamp": "var(--shadow-stamp)",
        "sticky": "var(--shadow-sticky)",
      },
      keyframes: {
        "ink-bleed": {
          "0%":   { transform: "scale(0.6)", opacity: "0" },
          "60%":  { transform: "scale(1.1)", opacity: "0.8" },
          "100%": { transform: "scale(1)",   opacity: "1" },
        },
        "page-turn": {
          "0%":   { transform: "rotateY(0deg)", opacity: "1" },
          "50%":  { transform: "rotateY(-90deg)", opacity: "0.3" },
          "100%": { transform: "rotateY(0deg)", opacity: "1" },
        },
        "settle": {
          "0%":   { transform: "rotate(-1deg) translateY(-4px)", opacity: "0" },
          "100%": { transform: "rotate(-1deg) translateY(0px)", opacity: "1" },
        },
        "fade-in": {
          "0%":   { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "ink-bleed": "ink-bleed 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "page-turn": "page-turn 0.5s ease-in-out",
        "settle": "settle 0.4s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
      },
    },
  },
  plugins: [],
}
