/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Nocturnal Archivist palette
        "background":                "#151311",
        "surface":                   "#151311",
        "surface-dim":               "#151311",
        "surface-bright":            "#3b3936",
        "surface-container-lowest":  "#100e0c",
        "surface-container-low":     "#1d1b19",
        "surface-container":         "#211f1d",
        "surface-container-high":    "#2c2927",
        "surface-container-highest": "#373432",
        "on-surface":                "#e7e1de",
        "on-surface-variant":        "#c3c8bd",
        "inverse-surface":           "#e7e1de",
        "inverse-on-surface":        "#32302e",
        "outline":                   "#8d9388",
        "outline-variant":           "#434840",
        "surface-tint":              "#abd1a1",
        "primary":                   "#abd1a1",
        "on-primary":                "#183715",
        "primary-container":         "#769a6e",
        "on-primary-container":      "#11300f",
        "inverse-primary":           "#45673f",
        "secondary":                 "#cdc6b6",
        "on-secondary":              "#343025",
        "secondary-container":       "#4d493d",
        "on-secondary-container":    "#bfb8a9",
        "secondary-fixed":           "#eae2d2",
        "secondary-fixed-dim":       "#cdc6b6",
        "tertiary":                  "#dcc497",
        "on-tertiary":               "#3d2e0e",
        "tertiary-container":        "#a38e65",
        "on-tertiary-container":     "#362808",
        "error":                     "#ffb4ab",
        "on-error":                  "#690005",
        "error-container":           "#93000a",
        "on-error-container":        "#ffdad6",
        "primary-fixed":             "#c7edbb",
        "primary-fixed-dim":         "#abd1a1",
        "on-primary-fixed":          "#022103",
        "on-primary-fixed-variant":  "#2e4e29",
        "on-secondary-fixed":        "#1f1b12",
        "on-secondary-fixed-variant": "#4b463b",
        "tertiary-fixed":            "#f9dfb1",
        "tertiary-fixed-dim":        "#dcc497",
        "on-tertiary-fixed":         "#261a00",
        "on-tertiary-fixed-variant": "#554422",
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans:  ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "page-margin": "4rem",
        "gutter": "2rem",
        "line-height-grid": "1.6rem",
        "stack-unit": "0.5rem",
      },
      boxShadow: {
        "paper": "0 4px 24px rgba(0,0,0,0.5), 0 1px 4px rgba(0,0,0,0.3)",
        "paper-lift": "0 8px 32px rgba(0,0,0,0.6), 0 2px 8px rgba(0,0,0,0.4)",
        "stamp": "inset 1px 1px 2px rgba(255,255,255,0.1), inset -1px -1px 2px rgba(0,0,0,0.3), 2px 2px 5px rgba(0,0,0,0.4)",
        "sticky": "3px 3px 10px rgba(0,0,0,0.4), 1px 1px 3px rgba(0,0,0,0.3)",
      },
      keyframes: {
        "ink-bleed": {
          "0%":   { transform: "scale(0.6)", opacity: "0" },
          "60%":  { transform: "scale(1.1)", opacity: "0.8" },
          "100%": { transform: "scale(1)",   opacity: "1" },
        },
        "page-turn": {
          "0%":   { transform: "rotateY(0deg)", opacity: "1" },
          "50%":  { transform: "rotateY(-90deg)", opacity: "0.3" },
          "100%": { transform: "rotateY(0deg)", opacity: "1" },
        },
        "settle": {
          "0%":   { transform: "rotate(-1deg) translateY(-4px)", opacity: "0" },
          "100%": { transform: "rotate(-1deg) translateY(0px)", opacity: "1" },
        },
        "fade-in": {
          "0%":   { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "ink-bleed": "ink-bleed 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "page-turn": "page-turn 0.5s ease-in-out",
        "settle": "settle 0.4s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
      },
    },
  },
  plugins: [],
}
