const express = require("express");
const cookieParser = require("cookie-parser");
const app = express();
const authRoutes = require("./routes/auth.routes");
const journalRoutes = require("./routes/journal.routes");
const challengeRoutes = require("./routes/challenge.routes");
const noteRoutes = require("./routes/notes.routes");
const progressRoutes = require("./routes/progress.routes");
const { errorMiddleware } = require("./middlewares/error.middleware");
app.use(express.json());
app.use(cookieParser());
app.use("/api/auth", authRoutes);
app.use("/api/journal", journalRoutes);
app.use("/api/challenge", challengeRoutes);
app.use("/api/notes", noteRoutes);
app.use("/api/progress", progressRoutes);
app.use(errorMiddleware);
module.exports = app;
