const express = require("express");
const cookieParser = require("cookie-parser");
const app = express();
const authRoutes = require("./routes/auth.routes");
const journalRoutes = require("./routes/journal.routes");
const { errorMiddleware } = require("./middlewares/error.middleware");
app.use(express.json());
app.use(cookieParser());
app.use("/api/auth", authRoutes);
app.use("/api/journal", journalRoutes);
app.use(errorMiddleware);
module.exports = app;
